"""Add Doctor Karma system models

Revision ID: 6a4b058a18e7
Revises: 5eda56c54719
Create Date: 2026-03-14 01:13:35.063102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a4b058a18e7'
down_revision: Union[str, Sequence[str], None] = '5eda56c54719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bias_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('group_a', sa.String(), nullable=True),
    sa.Column('group_b', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('audit_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bias_audits_id'), 'bias_audits', ['id'], unique=False)
    op.create_table('patient_karma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('complaint_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_karma_id'), 'patient_karma', ['id'], unique=False)
    op.create_index(op.f('ix_patient_karma_phone_number'), 'patient_karma', ['phone_number'], unique=True)
    op.create_table('patient_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('patient_phone', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('complaint_filed', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_phone'], ['patient_karma.phone_number'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['work_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_attendance_emp'), table_name='attendance')
    op.drop_index(op.f('idx_daily_scores_emp_date'), table_name='daily_scores')
    op.add_column('employees', sa.Column('complaint_count', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_employees_govt_id'), table_name='employees')
    op.drop_index(op.f('idx_fraud_flags_sub'), table_name='fraud_flags')
    op.drop_index(op.f('idx_grievances_emp'), table_name='grievances')
    op.alter_column('notifications', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('notifications_employee_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'employees', ['employee_id'], ['id'])
    op.add_column('work_submissions', sa.Column('patient_phone', sa.String(), nullable=True))
    op.drop_index(op.f('idx_work_submissions_emp'), table_name='work_submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_work_submissions_emp'), 'work_submissions', ['employee_id'], unique=False)
    op.drop_column('work_submissions', 'patient_phone')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_employee_id_fkey'), 'notifications', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notifications', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_grievances_emp'), 'grievances', ['employee_id'], unique=False)
    op.create_index(op.f('idx_fraud_flags_sub'), 'fraud_flags', ['submission_id'], unique=False)
    op.create_index(op.f('idx_employees_govt_id'), 'employees', ['govt_id'], unique=False)
    op.drop_column('employees', 'complaint_count')
    op.create_index(op.f('idx_daily_scores_emp_date'), 'daily_scores', ['employee_id', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_attendance_emp'), 'attendance', ['employee_id'], unique=False)
    op.drop_table('patient_reviews')
    op.drop_index(op.f('ix_patient_karma_phone_number'), table_name='patient_karma')
    op.drop_index(op.f('ix_patient_karma_id'), table_name='patient_karma')
    op.drop_table('patient_karma')
    op.drop_index(op.f('ix_bias_audits_id'), table_name='bias_audits')
    op.drop_table('bias_audits')
    # ### end Alembic commands ###
