"""Add scoring_rules table

Revision ID: 90441d1d9fb3
Revises: e6f25b2d57ab
Create Date: 2026-03-13 23:27:27.632928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90441d1d9fb3'
down_revision: Union[str, Sequence[str], None] = 'e6f25b2d57ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(), nullable=True),
    sa.Column('attendance_weight', sa.Float(), nullable=True),
    sa.Column('quality_weight', sa.Float(), nullable=True),
    sa.Column('count_weight', sa.Float(), nullable=True),
    sa.Column('context_bonus_formula', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_rules_dept_code'), 'scoring_rules', ['dept_code'], unique=True)
    op.create_index(op.f('ix_scoring_rules_id'), 'scoring_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_rules_id'), table_name='scoring_rules')
    op.drop_index(op.f('ix_scoring_rules_dept_code'), table_name='scoring_rules')
    op.drop_table('scoring_rules')
    # ### end Alembic commands ###
