"""Sync models with schema

Revision ID: e6f25b2d57ab
Revises: ee911cd94bd6
Create Date: 2026-03-13 17:31:19.470784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f25b2d57ab'
down_revision: Union[str, Sequence[str], None] = 'ee911cd94bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('streak_count', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('lockout_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'lockout_until')
    op.drop_column('employees', 'failed_login_attempts')
    op.drop_column('employees', 'streak_count')
    # ### end Alembic commands ###
